# Site settings
# bundle exec jekyll serve
title: Feng Ting Zhang
email: info@fengtingzhang.com
url: https://fengtingzhang.github.io/blog
description: "Main Page for Feng Ting Zhang's Hobby Website"
#baseurl: /blog

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Feng Ting Zhang

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fengtingzhang
  - title: github
    url: https://github.com/fengtingzhang
  - title: instagram 
    url: https://instagram.com/moreofsusan
  - title: linkedin
    url: https://www.linkedin.com/in/fengtingsusanzhang

# Prototypes I've experimented with
prototypes:
  - title: React
    url: https://platform-demo-9389.herokuapp.com/?q=Platforms
  - title: ElasticSearch
    url: https://floating-fortress-5275.herokuapp.com/?q=Platform
  - title: DashBoard
    url: https://platform-deploy-demo-4783.herokuapp.com/
  - title: My Recent Tweets
    url: https://pacific-wildwood-9343.herokuapp.com/
  - title: Marketing Site
    url: http://phyllispei.github.io/marketing/

# Cool things
favorites:
  - title: NER
    url: http://nlp.stanford.edu:8080/ner/
  - title: Meteor
    url: http://fengtingzhang.meteor.com/
  - title: Local Storage
    url: http://development.fengtingzhang-markie.divshot.io/

# Build settings
markdown: kramdown
permalink: pretty
