# Site settings
# bundle exec jekyll serve
title: Feng Ting Zhang
email: info@fengtingzhang.com
url: blog.fengtingzhang.com
description: "Main Page for Feng Ting Zhang's Hobby Website"
#baseurl: /blog

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Feng Ting Zhang

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/susanblueapron?tab=overview&from=2019-12-01&to=2019-12-31
  - title: linkedin
    url: https://www.linkedin.com/in/fengtingsusanzhang
  - title: instagram
    url: https://instagram.com/moreofsusan
  - title: twitter
    url: https://twitter.com/fengtingzhang

# Prototypes I've experimented with
# prototypes:
#  - title: Node+React
#    url: https://platform-demo-9389.herokuapp.com/?q=Platforms
#  - title: ElasticSearch+Node
#    url: https://floating-fortress-5275.herokuapp.com/?q=Platform
#  - title: A Deployment Dashboard
#    url: https://dashboard-deployment.herokuapp.com/
#  - title: Marketing Site
#    url: http://phyllispei.github.io/marketing/
#  - title: React over Github Pages
#    url: http://fengtingzhang.github.io/react-config-app/

# Cool things
favorites:
  - title: NER
    url: http://nlp.stanford.edu:8080/ner/
  - title: GitBook
    url: https://fengtingzhang.gitbooks.io/blog/content

# Build settings
markdown: kramdown
permalink: pretty
